spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  rsocket:
    server:
      port: 6969
      mapping-path: /rsocket
      transport: websocket
jwt:
  validity: 18000
  secret:
     key: ${SECRET_KEY}

popular:
  manga: fate-redline, vagabond, record-of-ragnarock, one-punch-man, eminence-in-shadow 

roles:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  user:
    username: ${USER_USERNAME}
    password: ${USER_PASSWORD}
logging:
    level:
        io:
         rsocket:
#           FrameLogger: DEBUG