server:
   port: ${PORT:8080}
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  rsocket:
    server:
      port: 6969
      mapping-path: /rsocket
      transport: websocket
jwt:
  validity: 18000
  secret:
     key: ${SECRET_KEY}

popular:
  manga: ${POPULAR:fate-redline, 20th-century-boys, record-of-ragnarock, one-punch-man, vagabond} 

roles:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:password}
  user:
    username: ${USER_USERNAME:user}
    password: ${USER_PASSWORD:password}
logging:
    level:
        org:
          mongodb:
            driver:
              cluster: OFF   
        io:
         rsocket:
#           FrameLogger: DEBUG