# This is a basic workflow to help you get started with Actions

name: Compile/Deploy Native Image To Heroku.
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

# Your workflows jobs.
jobs:
  Build-Image:
    concurrency:
      group: concurrency-group-1
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Multi-Stage Docker Build
        run: docker build -t manga-backend .

  # Prod-Release:
  #   environment: manga-spring.com
  #   concurrency:
  #     group: concurrency-group-2
  #     cancel-in-progress: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Release Image
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #       run: heroku container:release web -a manga-spring
