name: Compile/Deploy Native Image To Heroku.
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

# Your workflows jobs.
jobs:
  Build-Compile-Deploy:
    environment: manga-spring.com
    concurrency:
      group: concurrency-group-1
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "19"
          java-package: jdk
          architecture: x64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-mvn-

      - name: Build Artifact
        run: mvn clean package

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com/manga-spring/web
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Multi-Stage Docker Build And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.heroku.com/manga-spring/web

      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a manga-spring

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://www.manga-spring.com/home
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
