# This is a basic workflow to help you get started with Actions

name: Compile/Deploy Native Image To Heroku.
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Your workflows jobs.
jobs:
  Build-Compile-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "15"
          java-package: jdk 
          architecture: x64 

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Compile Native Image 
        run: mvn spring-boot:build-image

      - name: Upload Docker Image
        run: docker tag $(docker images --filter=reference=manga-backend --format "{{.ID}}") registry.heroku.com/manga-spring/web && docker push registry.heroku.com/manga-spring/web

      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run:  heroku container:login && heroku container:release web -a manga-spring







