name: Create Release
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

# Your workflows jobs.
jobs:
  # Release Job
  pre-release:
    name: "Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "16"
          java-package: jdk
          architecture: x64

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build Artifact
        run: mvn clean package

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Manga-Spring"
          files: |
            LICENSE.txt
            *.jar
